In [1]:
import pandas as panda
from matplotlib import pyplot as plot
import numpy as np
import seaborn as sns

In [2]:
train_data  = panda.read_csv('all_new/merchants.csv')

In [3]:
train_data.shape, train_data.merchant_id.unique().shape

((334696, 22), (334633,))

In [4]:
train_data.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
merchant_id,334696,334633,M_ID_6464db3b45,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
merchant_group_id,334696,NaN,NaN,NaN,31028.7,31623,1,3612,19900,51707.2,112586
merchant_category_id,334696,NaN,NaN,NaN,423.132,252.898,-1,222,373,683,891
subsector_id,334696,NaN,NaN,NaN,25.1164,9.80737,-1,19,27,33,41
numerical_1,334696,NaN,NaN,NaN,0.0114764,1.09815,-0.0574706,-0.0574706,-0.0574706,-0.0475558,183.735
numerical_2,334696,NaN,NaN,NaN,0.00810311,1.0705,-0.0574706,-0.0574706,-0.0574706,-0.0475558,182.079
category_1,334696,2,N,327657,NaN,NaN,NaN,NaN,NaN,NaN,NaN
most_recent_sales_range,334696,5,E,177104,NaN,NaN,NaN,NaN,NaN,NaN,NaN
most_recent_purchases_range,334696,5,E,175309,NaN,NaN,NaN,NaN,NaN,NaN,NaN
avg_sales_lag3,334683,NaN,NaN,NaN,13.833,2395.49,-82.13,0.88,1,1.16,851845
avg_purchases_lag3,334696,NaN,NaN,NaN,inf,NaN,0.333495,0.92365,1.01667,1.14652,inf
active_months_lag3,334696,NaN,NaN,NaN,2.99411,0.0952475,1,3,3,3,3
avg_sales_lag6,334683,NaN,NaN,NaN,21.6508,3947.11,-82.13,0.85,1.01,1.23,1.51396e+06
avg_purchases_lag6,334696,NaN,NaN,NaN,inf,NaN,0.167045,0.902247,1.02696,1.21558,inf
active_months_lag6,334696,NaN,NaN,NaN,5.9474,0.394936,1,6,6,6,6
avg_sales_lag12,334683,NaN,NaN,NaN,25.2277,5251.84,-82.13,0.85,1.02,1.29,2.56741e+06
avg_purchases_lag12,334696,NaN,NaN,NaN,inf,NaN,0.0983295,0.898333,1.04336,1.26648,inf
active_months_lag12,334696,NaN,NaN,NaN,11.5993,1.52014,1,12,12,12,12
category_4,334696,2,N,238596,NaN,NaN,NaN,NaN,NaN,NaN,NaN
city_id,334696,NaN,NaN,NaN,102.918,107.091,-1,-1,69,182,347
state_id,334696,NaN,NaN,NaN,11.8609,6.17689,-1,9,9,16,24
category_2,322809,NaN,NaN,NaN,2.38,1.56266,1,1,2,4,5

##### We can observe the following from merchants data

1. avg_purchases_lag12,avg_purchases_lag6, avg_purchases_lag3 all have np.inf values.which would require handling.
2. state_id, city_id, subsector_id, merchant_category_id have minimum values as -1. these indicate missing data

object data types are:

1. category_4

2. category_1

3. most_recent_sales_range

4. most_recent_purchases_range

In [7]:
train_data_dtypes = train_data.dtypes.to_frame().reset_index()
train_data_dtypes.columns = ['col_name','col_type']
train_data_dtypes

                       col_name col_type
0                   merchant_id   object
1             merchant_group_id    int64
2          merchant_category_id    int64
3                  subsector_id    int64
4                   numerical_1  float64
5                   numerical_2  float64
6                    category_1   object
7       most_recent_sales_range   object
8   most_recent_purchases_range   object
9                avg_sales_lag3  float64
10           avg_purchases_lag3  float64
11           active_months_lag3    int64
12               avg_sales_lag6  float64
13           avg_purchases_lag6  float64
14           active_months_lag6    int64
15              avg_sales_lag12  float64
16          avg_purchases_lag12  float64
17          active_months_lag12    int64
18                   category_4   object
19                      city_id    int64
20                     state_id    int64
21                   category_2  float64

In [8]:
train_data_dtypes[train_data_dtypes.col_type==np.object].col_name

0                     merchant_id
6                      category_1
7         most_recent_sales_range
8     most_recent_purchases_range
18                     category_4
Name: col_name, dtype: object

In [9]:
# ignoring merchant id lets analyze the rest of the fields such as category_1,most_recent_sales_range,most_recent_purchase_range,
# category_4

# check for empty values
train_data[train_data_dtypes[train_data_dtypes.col_type==np.object].col_name.values.tolist()].isnull().sum()

merchant_id                    0
category_1                     0
most_recent_sales_range        0
most_recent_purchases_range    0
category_4                     0
dtype: int64

In [10]:
train_data.category_1.value_counts()

N    327657
Y      7039
Name: category_1, dtype: int64

In [11]:
train_data['merchant_category_1_yes'] = train_data.category_1.apply(lambda x : 1 if x=='Y'else 0).astype(np.int64)
train_data['merchant_category_1_no'] = train_data.category_1.apply(lambda x : 1 if x=='N'else 0).astype(np.int64)

In [12]:
train_data.category_4.value_counts()

N    238596
Y     96100
Name: category_4, dtype: int64

In [13]:
train_data['merchant_category_4_yes'] = train_data.category_4.apply(lambda x : 1 if x=='Y'else 0).astype(np.int64)
train_data['merchant_category_4_no'] = train_data.category_4.apply(lambda x : 1 if x=='N'else 0).astype(np.int64)

In [14]:
train_data.most_recent_sales_range.value_counts()

E    177104
D    117475
C     34075
B      5037
A      1005
Name: most_recent_sales_range, dtype: int64

In [15]:
train_data['most_sales_range_E'] = train_data.most_recent_sales_range.apply(lambda x : 1 if x=='E'else 0).astype(np.int64)
train_data['most_sales_range_D'] = train_data.most_recent_sales_range.apply(lambda x : 1 if x=='D'else 0).astype(np.int64)
train_data['most_sales_range_C'] = train_data.most_recent_sales_range.apply(lambda x : 1 if x=='C'else 0).astype(np.int64)
train_data['most_sales_range_B'] = train_data.most_recent_sales_range.apply(lambda x : 1 if x=='B'else 0).astype(np.int64)
train_data['most_sales_range_A'] = train_data.most_recent_sales_range.apply(lambda x : 1 if x=='A'else 0).astype(np.int64)

In [16]:
train_data.most_recent_purchases_range.value_counts()

E    175309
D    119187
C     34144
B      5046
A      1010
Name: most_recent_purchases_range, dtype: int64

In [17]:
train_data['most_recent_purchases_range_E'] = train_data.most_recent_purchases_range.apply(lambda x : 1 if x=='E'else 0).astype(np.int64)
train_data['most_recent_purchases_range_D'] = train_data.most_recent_purchases_range.apply(lambda x : 1 if x=='D'else 0).astype(np.int64)
train_data['most_recent_purchases_range_C'] = train_data.most_recent_purchases_range.apply(lambda x : 1 if x=='C'else 0).astype(np.int64)
train_data['most_recent_purchases_range_B'] = train_data.most_recent_purchases_range.apply(lambda x : 1 if x=='B'else 0).astype(np.int64)
train_data['most_recent_purchases_range_A'] = train_data.most_recent_purchases_range.apply(lambda x : 1 if x=='A'else 0).astype(np.int64)

In [18]:

int_col_names = train_data_dtypes[train_data_dtypes.col_type==np.int64].col_name.values.tolist()
int_col_names

['merchant_group_id',
 'merchant_category_id',
 'subsector_id',
 'active_months_lag3',
 'active_months_lag6',
 'active_months_lag12',
 'city_id',
 'state_id']

In [19]:
train_data[int_col_names].isnull().any().sum()#no empty or nan values

0

In [34]:
##however -1 would indicate missing/outlier data for merchants ..let check the count of those

train_data[train_data.merchant_category_id==-1].shape,\
train_data[train_data.subsector_id==-1].shape,\
train_data[train_data.state_id==-1].shape,\
train_data[train_data.city_id==-1].shape,\
train_data.loc[(train_data.merchant_category_id==-1) &(train_data.subsector_id==-1)].shape,\
train_data.loc[(train_data.merchant_category_id==-1) &(train_data.subsector_id==-1)].shape,\
train_data.loc[(train_data.merchant_category_id==-1) &(train_data.subsector_id==-1)].merchant_id

((1, 36),
 (1, 36),
 (11887, 36),
 (105184, 36),
 (1, 36),
 (1, 36),
 2465    M_ID_a2cfe4149a
 Name: merchant_id, dtype: object)

I have decided not to handle -1 values as missing data in the state_id, city_id, merchant_category_id and subsector_id fields

In [35]:
train_data.merchant_group_id.unique()

array([  8353,   3184,    447, ..., 112528, 112393, 107283], dtype=int64)

In [36]:
train_data.merchant_category_id.unique()

array([792, 840, 690, 222,  87, 529, 813,  81, 369, 427,  63,  45,   2,
       278, 298, 497, 309, 705, 511, 437, 456, 781, 703, 360, 796, 412,
       332,  80, 630,  68, 591, 606, 683, 891, 560, 178, 290, 544, 823,
       692, 779,  33, 432, 818, 819, 842, 411,  19, 771,  34, 419, 884,
       184, 111, 434, 356, 367, 373, 631, 573, 652, 669, 531, 195, 130,
       836, 637, 670, 307, 215, 387, 506, 443, 774, 414, 166, 108, 607,
       451, 763, 806, 471, 518, 105,  60, 391, 557, 302, 154, 623, 333,
       847, 384,  78, 299, 342, 363, 101, 783,  90, 489, 737, 650, 261,
       556, 209, 454, 462,   9, 769, 561, 661, 289, 474, 180, 259,  14,
        40, 317, 273, 115, 507, 667, 216, 498, 422, 206, 613, 430, 110,
       574, 536, 653, 357, 274, 793, 171, 385, 472, 651,  56, 312, 119,
       201, 247, 554, 114, 873, 671, 190, 854, 530, 843, 527, 761, 320,
       276, 348, 743, 109, 315, 645,  16, 834, 415, 642,  83, 568,  49,
       223, 695, 696, 172, 702, 458, 748, 416, 330, 706, 340,  21, 469,
       267, 181, 225, 795, 241, 157, 605, 808, 734, 396,  71, 420, 145,
       409, 751,  52,  69, 717, 598, 246, 827, 551, 417, 345, 519, 265,
       504, 117, 480, 351, 482, 491, 513,  57, 580, 676,  -1, 614, 457,
       879,  18, 514, 593, 248, 210, 179, 685, 319, 126, 713, 383, 374,
       829, 534, 686, 755, 386, 478, 526, 198, 776, 839,  36, 401,  53,
       358, 268,  31, 162, 528, 187, 509, 224, 499, 140, 665, 542, 245,
        38, 398, 183, 587, 292, 438, 343, 656, 889, 803, 664, 400, 523,
       712, 814, 790, 393, 546, 662, 885, 266, 805, 881, 334, 131, 355,
       249, 628, 448, 566,  11, 141, 421, 599, 226, 322,  86, 260, 601,
       634, 281, 550, 757, 217, 741, 780, 714,  59, 436, 668,  67, 164,
       464, 381, 182, 579, 648, 718, 153, 725, 875, 789, 878, 583],
      dtype=int64)

In [37]:
temp = train_data.groupby(['merchant_id']).agg({'merchant_category_id':'nunique'}).reset_index()
temp[temp.merchant_category_id!=1]

##merchant and merchant cat id is a 1-many relationship

            merchant_id  merchant_category_id
130891  M_ID_645a6af169                     2

In [38]:
int_col_names

['merchant_group_id',
 'merchant_category_id',
 'subsector_id',
 'active_months_lag3',
 'active_months_lag6',
 'active_months_lag12',
 'city_id',
 'state_id']

In [39]:
train_data.subsector_id.unique(),train_data.city_id.unique(),train_data.state_id.unique()

(array([ 9, 20,  1, 21, 27, 29, 18, 37, 10, 33,  7, 15, 34,  2, 36, 17, 19,
        25, 12, 31, 38, 40, 32, 16, 41,  5, 30, 13, 22,  4, 23, 39,  8, 14,
         3, 26, 35, 24, -1, 11, 28], dtype=int64),
 array([242,  22,  -1, 160,  60, 248,  88, 158,  11, 143, 282, 123, 126,
        272,  85, 140,  62,  63, 323, 200, 310,  69, 239,  17,   4, 231,
        124,   3, 301,  87, 186, 150, 156, 161, 209,  25, 303, 101,  12,
        147,  44, 254,  58,  32,  53,  96, 213, 214, 125, 229, 168,  30,
        204,  94, 210, 137, 165, 187, 223, 238, 205, 157, 114, 276,  76,
        233, 183, 277, 212, 247, 167, 274, 343, 251, 283,   9,  21,  84,
          7, 297, 291,  33, 246, 169, 228, 201, 181, 253, 159, 172,  47,
          6, 113, 206,  51,  82,  80,  36, 215, 259, 314,  98, 295, 174,
        211, 339, 250, 307,  24,  48,  89, 341, 275,  66, 224, 189, 230,
        100, 142, 342, 135, 105, 115,  64, 153, 245, 299,  14, 184, 208,
        235, 219, 108, 119, 329, 163, 139, 220,  52,  10, 285, 337, 308,
        300, 155, 256, 271,   1, 333, 116, 136, 281,  56, 218,   8, 340,
        261, 146,  38, 106,  46, 325,  42, 226, 268,  90, 129, 289, 270,
         91, 130, 311, 216, 294, 278, 171, 336, 117, 148, 255, 288, 180,
        318, 203, 260, 110, 334,  41,  61, 232, 327, 151, 240,  78, 262,
         39, 166,  49,  23, 221,  97, 191, 128,  65, 133, 252, 190, 258,
        296,  16, 193, 293, 287,  70, 321, 131, 269, 236, 198, 309, 188,
         34, 175, 306, 347, 112, 234,  28,  86, 290, 267,  29,   2, 313,
         74,  68, 279, 182,  71, 338, 162, 104,  81,  83, 194, 144, 312,
         13,  26, 326, 328, 263, 145, 304, 345, 173, 286, 265, 120, 178,
        111,  40,  77, 237,  73,  35,  92, 118, 330,  18, 320], dtype=int64),
 array([ 9, 16,  5, -1, 21, 15, 20, 23, 18, 19,  4,  8,  1,  2, 22,  7,  6,
        13, 10, 24, 11, 14,  3, 12, 17], dtype=int64))

In [40]:
train_data.active_months_lag3.nunique(),train_data.active_months_lag6.nunique(),train_data.active_months_lag12.nunique()

(3, 6, 12)

In [41]:

float_col_names = train_data_dtypes[train_data_dtypes.col_type==np.float64].col_name.values.tolist()
float_col_names

['numerical_1',
 'numerical_2',
 'avg_sales_lag3',
 'avg_purchases_lag3',
 'avg_sales_lag6',
 'avg_purchases_lag6',
 'avg_sales_lag12',
 'avg_purchases_lag12',
 'category_2']

In [42]:
train_data[float_col_names].isnull().sum()

numerical_1                0
numerical_2                0
avg_sales_lag3            13
avg_purchases_lag3         0
avg_sales_lag6            13
avg_purchases_lag6         0
avg_sales_lag12           13
avg_purchases_lag12        0
category_2             11887
dtype: int64

In [43]:
mean_avg_sales_3 = np.mean(train_data[~train_data.avg_sales_lag3.isna()].avg_sales_lag3.values)
mean_avg_sales_6 = np.mean(train_data[~train_data.avg_sales_lag6.isna()].avg_sales_lag6.values)
mean_avg_sales_12 = np.mean(train_data[~train_data.avg_sales_lag12.isna()].avg_sales_lag12.values)

In [44]:
train_data.avg_sales_lag3.fillna(value= mean_avg_sales_3, inplace = True)
train_data.avg_sales_lag6.fillna(value= mean_avg_sales_6, inplace = True)
train_data.avg_sales_lag12.fillna(value= mean_avg_sales_12, inplace = True)

In [45]:
train_data.numerical_1.unique(),train_data.numerical_2.unique()#no idea what these negative numbers are

(array([-5.74706500e-02, -7.89613000e-03,  4.08529850e-01, -4.75557500e-02,
        -3.76408400e-02, -2.77259400e-02,  1.88585060e+00, -1.78110400e-02,
         2.56717061e+01,  2.01877000e-03,  1.19336800e-02,  4.16783900e-02,
         9.14189970e-01,  1.24138182e+00,  3.17634900e-02,  2.18485800e-02,
         6.15082000e-02,  1.85610589e+00,  1.11082720e-01,  1.50742340e-01,
         8.13380100e-02,  1.30912530e-01,  5.15932900e-02,  9.93509210e-01,
         2.59806290e-01,  7.14231000e-02,  5.37423610e-01,  1.01167820e-01,
         1.15231376e+01,  1.40827430e-01,  2.79636090e-01,  2.12380830e+00,
         3.88700040e-01,  2.00316860e-01,  1.90401960e-01,  2.42439599e+01,
         1.36827699e+02,  1.60657240e-01,  1.20997630e-01,  6.16742840e-01,
         1.80487050e-01,  9.12529100e-02,  3.29210620e-01,  2.39976480e-01,
         2.10231760e-01,  3.78785140e-01,  4.18444760e-01,  2.20146670e-01,
         2.69721190e-01,  3.19295710e-01,  3.58955330e-01,  1.28628073e+02,
         2.89551000e-01,  4.68019280e-01,  9.90700822e+00,  1.70572150e-01,
         2.30061570e-01,  4.48189470e-01,  3.68870230e-01,  2.49891380e-01,
         4.97763990e-01,  7.85296220e-01,  5.07678900e-01,  4.58104370e-01,
         2.99465900e-01,  5.67168320e-01,  3.49040430e-01,  3.98614950e-01,
         1.18189239e+00,  8.05126030e-01,  5.57253420e-01,  5.17593800e-01,
         7.75381310e-01,  9.73679400e-01,  4.28359660e-01,  5.86998130e-01,
         3.39125520e-01,  1.25129672e+00,  4.87849090e-01,  1.07282844e+00,
         4.38274560e-01,  8.15040930e-01,  1.53882895e+00,  1.31078615e+00,
         1.16206258e+00,  6.36572650e-01,  5.96913030e-01,  6.96062080e-01,
         7.95211120e-01,  1.04308373e+00,  6.56402460e-01,  8.84445260e-01,
         6.06827940e-01,  3.09380810e-01,  4.77934180e-01,  1.14223277e+00,
         1.51899914e+00,  8.34870740e-01,  6.86147170e-01,  9.53849590e-01,
         5.27508700e-01,  1.52891404e+00,  5.77083230e-01,  1.35044577e+00,
         2.13372321e+00,  1.59831837e+00,  1.94534003e+00,  6.66317360e-01,
         7.35721700e-01,  5.47338510e-01,  9.83594300e-01,  2.28244677e+00,
         1.09265825e+00,  7.45636600e-01,  1.29095634e+00,  1.54874385e+00,
         6.46487560e-01,  1.38019048e+00,  1.91559531e+00,  8.94360160e-01,
         6.26657750e-01,  6.76232270e-01,  2.73853237e+00,  2.90708575e+00,
         7.25806790e-01,  3.17478817e+00,  2.77819199e+00,  8.74530360e-01,
         9.43934690e-01,  2.57989391e+00,  9.24104880e-01,  8.54700550e-01,
         9.63764500e-01,  7.65466410e-01,  8.64615450e-01,  1.74704194e+00,
         9.34019780e-01,  7.55551500e-01,  7.15891890e-01,  2.01474436e+00,
         1.63797799e+00,  7.05976980e-01,  1.10257316e+00,  8.44785640e-01,
         2.18329773e+00,  1.03316883e+00,  1.08274335e+00,  8.24955830e-01,
         1.13231787e+00,  2.52040448e+00,  3.96798051e+00,  1.05299863e+00,
         1.02325392e+00,  1.26121163e+00,  1.06291354e+00,  1.00342411e+00,
         1.19180730e+00,  1.12240297e+00,  1.56857366e+00,  1.66772270e+00,
         1.01333902e+00,  1.20172220e+00,  1.17197749e+00,  3.64078867e+00,
         3.02606460e+00,  9.04275070e-01,  1.36036067e+00,  1.49916933e+00,
         1.15214768e+00,  3.51189491e+00,  1.39010538e+00,  1.23146691e+00,
         1.45950971e+00,  1.47933952e+00,  1.28104143e+00,  1.21163710e+00,
         2.35185111e+00,  1.32070105e+00,  1.80653137e+00,  4.05721465e+00,
         1.30087124e+00,  1.40993519e+00,  1.44959481e+00,  2.03457417e+00,
         1.67763761e+00,  1.89576550e+00,  3.82917185e+00,  3.12521364e+00,
         1.34053086e+00,  3.40283097e+00,  3.65070358e+00,  1.40002029e+00,
         2.16346792e+00,  1.71729723e+00,  1.22155201e+00,  2.02465926e+00,
         1.58840347e+00,  1.43967990e+00,  1.11248806e+00,  1.48925443e+00,
         2.07423378e+00,  2.00482945e+00,  1.69746742e+00,  2.04448907e+00,
         1.65780780e+00,  1.27112653e+00,  1.81644627e+00,  1.75695684e+00,
         1.37027557e+00,  6.00053591e+00,  1.50908423e+00,  2.15355302e+00,
         3.53172472e+00,  2.33202130e+00,  1.78670156e+00,  1.33061596e+00,
         2.22295735e+00,  7.73564417e+00,  1.41985010e+00,  1.61814818e+00,
         2.17338283e+00,  2.24278716e+00,  2.36176601e+00,  3.06572422e+00,
         1.62806309e+00,  1.92551022e+00,  1.60823328e+00,  2.44108524e+00,
         3.52180982e+00,  2.21304244e+00,  8.86594327e+00,  2.96657518e+00,
         2.08414869e+00,  2.38159582e+00,  2.43117034e+00,  1.96516984e+00,
         1.68755251e+00,  2.80793671e+00,  5.36598203e+00,  2.41134053e+00,
         2.23287225e+00,  2.25270206e+00,  3.15495836e+00,  2.32210639e+00,
         1.79661646e+00,  2.45100015e+00,  2.66912804e+00,  1.93542512e+00,
         2.71870257e+00,  1.76687175e+00,  1.42976500e+00,  2.99631989e+00,
         1.73712704e+00,  1.72721213e+00,  2.76827709e+00,  1.46942462e+00,
         1.87593570e+00,  8.08266582e+00,  1.55865876e+00,  2.34193620e+00,
         1.98499964e+00,  3.03597951e+00,  2.47082996e+00,  1.82636117e+00,
         2.20312754e+00,  2.06431888e+00,  3.19461798e+00,  3.28385211e+00,
         1.86602079e+00,  2.56006410e+00,  4.32491707e+00,  4.00764013e+00,
         5.14785413e+00,  2.39151072e+00,  3.62095886e+00,  2.95666027e+00,
         2.58980881e+00,  2.55014919e+00,  1.77678665e+00,  3.38300116e+00,
         3.24419250e+00,  1.97508474e+00,  1.57848857e+00,  1.90568041e+00,
         2.54023429e+00,  3.49206511e+00,  2.10397850e+00,  2.98640498e+00,
         3.34334154e+00,  3.36317135e+00,  1.64789290e+00,  2.09406359e+00,
         2.74844728e+00,  3.23427759e+00,  1.99491455e+00,  3.29376702e+00,
         4.24559784e+00,  3.43257568e+00,  2.26261697e+00,  4.40423631e+00,
         2.78810690e+00,  2.37168091e+00,  2.53031938e+00,  2.62946843e+00,
         3.70027810e+00,  3.45240549e+00,  2.31219149e+00,  3.16487326e+00,
         2.49065977e+00,  9.09398607e+00,  2.81785161e+00,  1.83627608e+00,
         2.48074486e+00,  2.14363811e+00,  2.40142563e+00,  3.84900166e+00,
         3.72010791e+00,  2.30227658e+00,  3.33342664e+00,  2.88725594e+00,
         2.94674537e+00,  4.62236420e+00,  2.19321264e+00,  2.11389340e+00,
         2.83768142e+00,  3.83908676e+00,  3.56146944e+00,  1.58856955e+01,
         5.46513107e+00,  3.78951224e+00,  3.61104396e+00,  2.05440397e+00,
         2.42125544e+00,  3.39291606e+00,  3.09546893e+00,  1.70738232e+00,
         3.10538384e+00,  4.03738485e+00,  3.11529874e+00,  4.97930076e+00,
         2.61955352e+00,  2.82776651e+00,  3.30368192e+00,  2.56997900e+00,
         2.86742613e+00,  3.42266078e+00,  4.25551274e+00,  2.59972371e+00,
         4.11670408e+00,  3.04589441e+00,  5.12802432e+00,  2.65921314e+00,
         4.38440650e+00,  2.46091505e+00,  3.54163963e+00,  1.84619098e+00,
         3.00623479e+00,  2.63938333e+00,  3.50198001e+00,  2.51048957e+00,
         2.29236168e+00,  4.69176853e+00,  2.84759632e+00,  4.09687427e+00,
         3.25410740e+00,  3.46232039e+00,  3.32351173e+00,  3.48215020e+00,
         2.27253187e+00,  4.33483198e+00,  2.68895785e+00,  3.41274587e+00,
         3.85891657e+00,  4.21585312e+00,  1.95525493e+00,  3.71019300e+00,
         4.07704446e+00,  3.57138434e+00,  2.67904295e+00,  2.89717084e+00,
         3.20453288e+00,  2.87734104e+00,  2.69887276e+00,  3.05580931e+00,
         7.88436773e+00,  3.76968243e+00,  2.70878766e+00,  4.88015172e+00,
         2.85751123e+00,  3.68044829e+00,  3.81925695e+00,  6.76398354e+00,
         3.77959733e+00,  3.27393721e+00,  2.64929824e+00,  7.67615474e+00,
         6.18891909e+00,  3.07563912e+00,  2.72861747e+00,  4.14644879e+00,
         7.71581436e+00,  3.73993771e+00,  5.49487579e+00,  3.01614970e+00,
         6.05011043e+00,  2.60963862e+00,  5.03879019e+00,  6.39713208e+00,
         4.28525745e+00,  6.06002533e+00,  5.09827961e+00,  6.57560036e+00,
         4.15636370e+00,  4.80083248e+00,  3.22436269e+00,  4.91981133e+00,
         3.14504345e+00,  7.02177106e+00,  2.75836218e+00,  2.92691556e+00,
         3.35325644e+00,  3.73002281e+00,  2.50057467e+00,  3.59121415e+00,
         1.18701593e+01,  5.80223782e+00,  4.19602331e+00,  4.66202382e+00,
         3.89857618e+00,  5.50479069e+00,  4.99913057e+00,  2.79802180e+00,
         4.61244930e+00,  3.86883147e+00,  3.13512855e+00,  7.29938838e+00,
         7.36879271e+00,  4.01755504e+00,  3.47223530e+00,  3.75976752e+00,
         3.31359683e+00,  4.35466178e+00,  4.26542765e+00,  3.65979308e+01,
         2.91700065e+00,  4.52321516e+00,  3.91840599e+00,  3.93823580e+00,
         6.64500469e+00,  4.72151325e+00,  4.49347045e+00,  2.93683046e+00,
         1.01350510e+01,  5.77249311e+00,  4.29517236e+00,  4.63227911e+00,
         5.26683299e+00,  3.55155453e+00,  9.55998657e+00,  7.99343168e+00,
         4.87023681e+00,  3.80934205e+00,  4.55295987e+00,  3.98781032e+00,
         1.00359020e+01,  5.25691808e+00,  6.96228163e+00,  4.57278968e+00,
         4.81074738e+00,  7.98351678e+00,  8.20164467e+00,  4.36457669e+00,
         3.87874638e+00,  4.08695937e+00,  3.95806561e+00,  3.67053338e+00,
         3.88866128e+00,  4.12661898e+00,  3.94815071e+00,  3.92832090e+00,
         5.05861999e+00,  4.41415121e+00,  5.34615222e+00,  4.89006662e+00,
         5.17759885e+00,  4.74134305e+00,  1.79479956e+01,  5.53453540e+00,
         3.60112905e+00,  5.57419502e+00,  5.73283349e+00,  4.10678918e+00,
         6.49628113e+00,  3.97789542e+00,  3.18470307e+00,  4.94955605e+00,
         4.18610841e+00,  7.01185615e+00,  4.20593822e+00,  4.53313006e+00,
         8.12232544e+00,  6.37730227e+00,  9.95658274e+00,  5.97079119e+00,
         4.45381083e+00,  5.79232292e+00,  6.41696189e+00,  4.59261949e+00,
         3.63087377e+00,  5.19742865e+00,  5.90138686e+00,  4.43398102e+00,
         3.08555403e+00,  7.22998405e+00,  4.16627860e+00,  4.54304497e+00,
         4.06712956e+00,  3.90849109e+00,  5.87164215e+00,  8.19172977e+00,
         4.17619351e+00,  5.72291859e+00,  8.81636874e+00,  5.59402483e+00,
         5.91130177e+00,  6.66483450e+00,  8.04300620e+00,  5.30649260e+00,
         5.27674789e+00,  7.40845233e+00,  2.31235757e+01,  5.08836471e+00,
         1.08984987e+01,  4.31500217e+00,  6.25832342e+00,  1.05911366e+01,
         5.01896038e+00,  4.64219401e+00,  5.42547145e+00,  5.11810942e+00,
         3.69036319e+00,  5.94104648e+00,  6.29798304e+00,  5.40564165e+00,
         7.39853742e+00,  6.43679170e+00,  5.86172725e+00,  4.34474688e+00,
         7.87445283e+00,  5.76257820e+00,  6.36738737e+00,  4.65210892e+00,
         4.39432140e+00,  4.93964114e+00,  4.30508726e+00,  3.79942714e+00,
         5.07844980e+00,  4.76117286e+00,  5.18751375e+00,  5.16768394e+00,
         1.04919876e+01,  4.44389592e+00,  6.51611093e+00,  1.25245430e+01,
         5.48496088e+00,  7.20023933e+00,  5.64359935e+00,  5.54445031e+00,
         4.46372573e+00,  8.59824085e+00,  6.63508979e+00,  4.73142815e+00,
         4.75125796e+00,  8.26113410e+00,  4.82066229e+00,  7.03168596e+00,
         5.00904547e+00,  6.02036572e+00,  3.26402231e+00,  5.32632241e+00,
         6.11951476e+00,  5.23708827e+00,  1.30996074e+01,  4.68185363e+00,
         8.09258073e+00,  8.96509231e+00,  1.77695274e+01,  6.08977005e+00,
         6.94245182e+00,  7.82487831e+00,  1.65202494e+01,  5.24700318e+00,
         5.75266330e+00,  1.27724156e+01,  6.44670660e+00,  6.48636622e+00,
         6.53594074e+00,  6.04019552e+00,  8.17189996e+00,  6.14925947e+00,
         1.25741175e+01,  9.76819956e+00,  5.65351426e+00,  9.77811447e+00,
         2.00400405e+01,  1.93559121e+01,  9.48066734e+00,  6.91270711e+00,
         1.37837358e+01,  4.77108777e+00,  8.82628365e+00,  9.21296492e+00,
         9.75828466e+00,  5.43538636e+00,  4.51330025e+00,  6.42687679e+00,
         5.44530126e+00,  4.95947095e+00,  6.26823833e+00,  1.66888028e+01,
         7.44811194e+00,  8.25121920e+00,  5.33623732e+00,  1.03630938e+01,
         6.24840852e+00,  1.17908400e+01,  6.20874890e+00,  8.46934709e+00,
         4.96938585e+00,  5.71300368e+00,  8.87585817e+00,  7.59683551e+00,
         6.85321768e+00,  3.37308625e+00,  1.00755616e+01,  6.22857871e+00,
         7.46794175e+00,  1.12851799e+01,  7.08126048e+00,  7.13083500e+00,
         7.70589946e+00,  5.51470559e+00,  9.17330530e+00,  7.58692060e+00,
         8.41977257e+00,  6.23849361e+00,  5.92121667e+00,  6.86313259e+00,
         1.06902857e+01,  8.21155958e+00,  7.25972876e+00,  6.58551526e+00,
         7.15066481e+00,  8.53875142e+00,  8.97500721e+00,  5.22717337e+00,
         9.71862504e+00,  1.99309765e+01,  7.33904800e+00,  5.69317387e+00,
         7.24981386e+00,  1.38927998e+01,  5.52462050e+00,  6.01045081e+00,
         8.70730480e+00,  1.13149246e+01,  6.70449412e+00,  5.68325897e+00,
         5.29657770e+00,  6.19883399e+00,  1.21180319e+01,  6.06994024e+00,
         1.91080395e+01,  1.14140737e+01,  5.45521617e+00,  7.47785666e+00,
         1.06803708e+01,  9.30219906e+00,  1.11662011e+01,  7.04160086e+00,
         6.81355806e+00,  7.00194125e+00,  1.00061573e+01,  9.13364568e+00,
         9.85743370e+00,  6.28806813e+00,  2.05556155e+01,  9.99624236e+00,
         6.79372826e+00,  6.38721718e+00,  7.45802685e+00,  5.58410992e+00,
         4.70168344e+00,  7.63649513e+00,  5.88155706e+00,  4.60253439e+00,
         1.26930963e+01,  4.23568293e+00,  1.22568406e+01,  8.05292111e+00,
         1.16916910e+01,  6.16908928e+00,  1.41208426e+01,  7.41836723e+00,
         7.78521869e+00,  5.20734356e+00,  7.18040953e+00,  9.02458174e+00,
         1.64607600e+01,  1.09778179e+01,  4.37449159e+00,  6.98211144e+00,
         8.88577307e+00,  1.17710102e+01,  1.21279468e+01,  1.18503295e+01,
         7.92402735e+00,  1.36746719e+01,  1.50131840e+01,  8.39002786e+00,
         7.76538888e+00,  1.12752650e+01,  8.64781537e+00,  9.12373078e+00,
         8.40985767e+00,  1.22766704e+01,  2.27468094e+01,  3.21362238e+01,
         1.05118174e+01,  1.47256517e+01,  9.26253944e+00,  7.80504850e+00,
         1.23758194e+01,  7.95377207e+00,  9.18322021e+00,  1.24154790e+01,
         3.24535007e+01,  1.03928385e+01,  8.57841104e+00,  7.35887780e+00,
         2.05952751e+01,  8.00334659e+00,  7.43819704e+00,  1.47058219e+01,
         9.35177358e+00,  1.37341613e+01,  1.28120752e+01,  1.11860309e+01,
         1.26831814e+01,  1.06208813e+01,  8.60815575e+00,  1.10174775e+01,
         1.10769669e+01,  1.35358632e+01,  1.61930576e+01,  1.81661235e+01,
         8.50900671e+00,  1.38630551e+01,  9.62939090e+00,  2.31334906e+01,
         8.72713460e+00,  8.69738989e+00,  7.55717589e+00,  1.45273537e+01,
         1.09976477e+01,  9.52032695e+00,  1.96236145e+01,  9.65913561e+00,
         7.19032443e+00,  1.25344579e+01,  1.05217323e+01,  1.13050097e+01,
         1.72043778e+01,  1.40415233e+01,  1.05812217e+01,  8.36028314e+00,
         1.20585425e+01,  1.08191794e+01,  1.38333103e+01,  7.28947347e+00,
         8.32062353e+00,  8.48917690e+00,  1.58063763e+01,  9.86734861e+00,
         1.04622429e+01,  8.83619855e+00,  9.69879523e+00,  9.96649765e+00,
         1.50230989e+01,  1.98814020e+01,  2.09323819e+01,  9.41126301e+00,
         1.07002006e+01,  1.11959458e+01,  1.20684574e+01,  1.38531402e+01,
         7.62658022e+00,  1.53899503e+01,  1.32780757e+01,  1.93856568e+01,
         1.44381195e+01,  6.69457921e+00,  1.23659045e+01,  1.44083748e+01,
         1.35854377e+01,  9.58973128e+00,  1.38035656e+01,  1.30401180e+01,
         1.13347545e+01,  2.48487691e+01,  1.34763738e+01,  1.73035269e+01,
         1.05514770e+01,  9.37160339e+00,  1.12950948e+01,  1.59253552e+01,
         1.88105923e+01,  2.02482535e+01,  9.24270963e+00,  1.60245042e+01,
         2.38572787e+01,  9.60956109e+00,  6.95236673e+00,  1.58757806e+01,
         1.70754841e+01,  1.52015672e+01,  1.21477766e+01,  2.01292746e+01,
         1.65797388e+01,  1.46066729e+01,  1.98714871e+01,  1.21378617e+01,
         1.33177353e+01,  1.93063375e+01,  2.34309378e+01,  1.21973511e+01,
         1.19098189e+01,  2.66136221e+01,  5.36416513e+01,  2.38176190e+01,
         9.03449664e+00,  2.06448496e+01,  1.23163300e+01,  1.21775213e+01,
         1.39027147e+01,  1.60641638e+01,  1.58658657e+01,  1.14834780e+01,
         7.64459313e+01,  1.53304609e+01,  1.15429674e+01,  9.15347549e+00,
         1.56973124e+01,  1.82454428e+01,  1.78785913e+01,  1.36350123e+01,
         1.61633129e+01,  1.17511804e+01,  1.71548033e+01,  5.06076906e+01,
         1.92666779e+01,  1.47454815e+01,  2.59096639e+01,  1.58559508e+01,
         1.40216935e+01,  2.05060410e+01,  2.31434055e+01,  4.26063628e+01,
         1.63318662e+01,  1.37936507e+01,  1.53502907e+01,  1.80669745e+01,
         2.51759609e+01,  1.38828849e+01,  2.69308990e+01,  1.94947207e+01,
         1.62327172e+01,  4.93088381e+01,  1.70655692e+01,  1.48248008e+01,
         2.57411105e+01,  1.95839549e+01,  1.97624232e+01,  2.67821754e+01,
         1.91179544e+01,  1.29112242e+01,  1.82256130e+01,  1.90683798e+01,
         2.30740012e+01,  2.34705974e+01,  3.56361850e+01,  2.21023406e+01,
         2.42340450e+01,  1.33871396e+01,  3.09365204e+01,  1.75613144e+01,
         3.64591221e+01,  1.04386132e+02,  2.18346382e+01,  3.22056281e+01,
         4.73655169e+01,  3.13529463e+01,  1.76406336e+01,  1.98020828e+01,
         4.32805763e+01,  2.18048935e+01,  2.60583874e+01,  3.15214997e+01,
         2.66532817e+01,  2.13388929e+01,  3.56560148e+01,  4.61459836e+01,
         2.64847283e+01,  3.11447333e+01,  3.61616749e+01,  3.39903109e+01,
         1.56774826e+01,  2.75257933e+01,  4.62451327e+01,  3.86007414e+01,
         2.79422192e+01,  4.93187530e+01,  2.75753678e+01,  5.21940753e+01,
         7.43241418e+01,  4.28145758e+01,  5.01218603e+01,  3.03019665e+01,
         4.51346634e+01,  7.09530743e+01,  5.49504187e+01,  4.33499806e+01,
         5.36515662e+01,  4.04746583e+01,  4.19222344e+01,  8.22957249e+01,
         5.97194877e+01,  4.05638925e+01,  4.14760637e+01,  8.20181076e+01,
         4.84164967e+01,  6.45282163e+01,  9.94881691e+01,  6.48950678e+01,
         1.50430948e+02,  5.68342505e+01,  6.73837088e+01,  8.01640205e+01,
         1.05585835e+02,  1.29322116e+02,  1.83735111e+02,  1.07648135e+02,
         1.17830742e+02,  1.72719653e+02]),
 array([-5.74706500e-02, -7.89613000e-03,  4.08529850e-01, -4.75557500e-02,
        -3.76408400e-02, -2.77259400e-02,  1.88585060e+00, -1.78110400e-02,
         2.43133642e+01,  2.01877000e-03,  1.19336800e-02,  4.16783900e-02,
         9.14189970e-01,  1.24138182e+00,  3.17634900e-02,  2.18485800e-02,
         6.15082000e-02,  1.85610589e+00,  1.50742340e-01,  8.13380100e-02,
         5.15932900e-02,  9.93509210e-01,  2.59806290e-01,  7.14231000e-02,
         5.37423610e-01,  1.01167820e-01,  1.12653501e+01,  1.40827430e-01,
         2.79636090e-01,  2.12380830e+00,  2.00316860e-01,  1.80487050e-01,
         2.38473637e+01,  1.19278318e+02,  1.60657240e-01,  1.11082720e-01,
         1.20997630e-01,  6.16742840e-01,  9.12529100e-02,  3.29210620e-01,
         2.39976480e-01,  2.10231760e-01,  3.68870230e-01,  4.18444760e-01,
         2.69721190e-01,  3.09380810e-01,  3.19295710e-01,  1.30912530e-01,
         3.58955330e-01,  1.08897413e+02,  2.89551000e-01,  4.58104370e-01,
         9.79794428e+00,  1.90401960e-01,  1.70572150e-01,  2.30061570e-01,
         4.38274560e-01,  2.20146670e-01,  3.88700040e-01,  2.49891380e-01,
         4.97763990e-01,  7.75381310e-01,  5.07678900e-01,  5.67168320e-01,
         3.49040430e-01,  3.98614950e-01,  4.48189470e-01,  1.17197749e+00,
         8.05126030e-01,  5.57253420e-01,  5.17593800e-01,  2.99465900e-01,
         9.53849590e-01,  4.28359660e-01,  5.86998130e-01,  3.39125520e-01,
         1.25129672e+00,  4.87849090e-01,  1.06291354e+00,  4.68019280e-01,
         8.15040930e-01,  1.53882895e+00,  1.31078615e+00,  1.16206258e+00,
         6.36572650e-01,  9.63764500e-01,  5.96913030e-01,  1.15214768e+00,
         7.95211120e-01,  1.04308373e+00,  6.46487560e-01,  8.84445260e-01,
         6.06827940e-01,  4.77934180e-01,  1.12240297e+00,  1.46942462e+00,

In [46]:
train_data[float_col_names].isnull().sum()

numerical_1                0
numerical_2                0
avg_sales_lag3             0
avg_purchases_lag3         0
avg_sales_lag6             0
avg_purchases_lag6         0
avg_sales_lag12            0
avg_purchases_lag12        0
category_2             11887
dtype: int64

In [47]:
most_appearing = train_data.category_2.value_counts().idxmax()
train_data.category_2.fillna(value=most_appearing, inplace= True)

In [48]:
train_data.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
merchant_id,334696,334633,M_ID_6464db3b45,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
merchant_group_id,334696,NaN,NaN,NaN,31028.7,31623,1,3612,19900,51707.2,112586
merchant_category_id,334696,NaN,NaN,NaN,423.132,252.898,-1,222,373,683,891
subsector_id,334696,NaN,NaN,NaN,25.1164,9.80737,-1,19,27,33,41
numerical_1,334696,NaN,NaN,NaN,0.0114764,1.09815,-0.0574706,-0.0574706,-0.0574706,-0.0475558,183.735
numerical_2,334696,NaN,NaN,NaN,0.00810311,1.0705,-0.0574706,-0.0574706,-0.0574706,-0.0475558,182.079
category_1,334696,2,N,327657,NaN,NaN,NaN,NaN,NaN,NaN,NaN
most_recent_sales_range,334696,5,E,177104,NaN,NaN,NaN,NaN,NaN,NaN,NaN
most_recent_purchases_range,334696,5,E,175309,NaN,NaN,NaN,NaN,NaN,NaN,NaN
avg_sales_lag3,334696,NaN,NaN,NaN,13.833,2395.44,-82.13,0.88,1,1.16,851845
avg_purchases_lag3,334696,NaN,NaN,NaN,inf,NaN,0.333495,0.92365,1.01667,1.14652,inf
active_months_lag3,334696,NaN,NaN,NaN,2.99411,0.0952475,1,3,3,3,3
avg_sales_lag6,334696,NaN,NaN,NaN,21.6508,3947.03,-82.13,0.85,1.01,1.23,1.51396e+06
avg_purchases_lag6,334696,NaN,NaN,NaN,inf,NaN,0.167045,0.902247,1.02696,1.21558,inf
active_months_lag6,334696,NaN,NaN,NaN,5.9474,0.394936,1,6,6,6,6
avg_sales_lag12,334696,NaN,NaN,NaN,25.2277,5251.74,-82.13,0.85,1.02,1.29,2.56741e+06
avg_purchases_lag12,334696,NaN,NaN,NaN,inf,NaN,0.0983295,0.898333,1.04336,1.26648,inf
active_months_lag12,334696,NaN,NaN,NaN,11.5993,1.52014,1,12,12,12,12
category_4,334696,2,N,238596,NaN,NaN,NaN,NaN,NaN,NaN,NaN
city_id,334696,NaN,NaN,NaN,102.918,107.091,-1,-1,69,182,347
state_id,334696,NaN,NaN,NaN,11.8609,6.17689,-1,9,9,16,24
category_2,334696,NaN,NaN,NaN,2.33099,1.55577,1,1,1,4,5
merchant_category_1_yes,334696,NaN,NaN,NaN,0.021031,0.143488,0,0,0,0,1
merchant_category_1_no,334696,NaN,NaN,NaN,0.978969,0.143488,0,1,1,1,1
merchant_category_4_yes,334696,NaN,NaN,NaN,0.287126,0.452422,0,0,0,1,1
merchant_category_4_no,334696,NaN,NaN,NaN,0.712874,0.452422,0,0,1,1,1
most_sales_range_E,334696,NaN,NaN,NaN,0.529149,0.49915,0,0,1,1,1
most_sales_range_D,334696,NaN,NaN,NaN,0.35099,0.477281,0,0,0,1,1
most_sales_range_C,334696,NaN,NaN,NaN,0.101809,0.302397,0,0,0,0,1
most_sales_range_B,334696,NaN,NaN,NaN,0.0150495,0.12175,0,0,0,0,1
most_sales_range_A,334696,NaN,NaN,NaN,0.00300272,0.0547149,0,0,0,0,1
most_recent_purchases_range_E,334696,NaN,NaN,NaN,0.523786,0.499435,0,0,1,1,1
most_recent_purchases_range_D,334696,NaN,NaN,NaN,0.356105,0.478848,0,0,0,1,1
most_recent_purchases_range_C,334696,NaN,NaN,NaN,0.102015,0.302668,0,0,0,0,1
most_recent_purchases_range_B,334696,NaN,NaN,NaN,0.0150764,0.121857,0,0,0,0,1
most_recent_purchases_range_A,334696,NaN,NaN,NaN,0.00301766,0.0548504,0,0,0,0,1

In [49]:
train_data.drop(columns = ['most_recent_sales_range','most_recent_purchases_range'], inplace = True)

In [50]:
avg_purchases_lag3_mean = np.mean(train_data[train_data.avg_purchases_lag3!=np.inf].avg_purchases_lag3.values)
avg_purchases_lag6_mean = np.mean(train_data[train_data.avg_purchases_lag6!=np.inf].avg_purchases_lag6.values)
avg_purchases_lag12_mean = np.mean(train_data[train_data.avg_purchases_lag12!=np.inf].avg_purchases_lag12.values)
avg_purchases_lag3_mean,avg_purchases_lag6_mean,avg_purchases_lag12_mean

(1.5907620965243672, 1.8875678157761595, 2.0791954108497936)

In [52]:
train_data.avg_purchases_lag3.replace(np.inf , avg_purchases_lag3_mean, inplace = True)
train_data.avg_purchases_lag6.replace(np.inf , avg_purchases_lag6_mean, inplace = True)
train_data.avg_purchases_lag12.replace(np.inf , avg_purchases_lag12_mean, inplace = True)

In [53]:
train_data.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
merchant_id,334696,334633,M_ID_6464db3b45,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
merchant_group_id,334696,NaN,NaN,NaN,31028.7,31623,1,3612,19900,51707.2,112586
merchant_category_id,334696,NaN,NaN,NaN,423.132,252.898,-1,222,373,683,891
subsector_id,334696,NaN,NaN,NaN,25.1164,9.80737,-1,19,27,33,41
numerical_1,334696,NaN,NaN,NaN,0.0114764,1.09815,-0.0574706,-0.0574706,-0.0574706,-0.0475558,183.735
numerical_2,334696,NaN,NaN,NaN,0.00810311,1.0705,-0.0574706,-0.0574706,-0.0574706,-0.0475558,182.079
category_1,334696,2,N,327657,NaN,NaN,NaN,NaN,NaN,NaN,NaN
avg_sales_lag3,334696,NaN,NaN,NaN,13.833,2395.44,-82.13,0.88,1,1.16,851845
avg_purchases_lag3,334696,NaN,NaN,NaN,1.59076,107.187,0.333495,0.92365,1.01667,1.14652,61851.3
active_months_lag3,334696,NaN,NaN,NaN,2.99411,0.0952475,1,3,3,3,3
avg_sales_lag6,334696,NaN,NaN,NaN,21.6508,3947.03,-82.13,0.85,1.01,1.23,1.51396e+06
avg_purchases_lag6,334696,NaN,NaN,NaN,1.88757,97.8624,0.167045,0.902247,1.02696,1.21558,56077.5
active_months_lag6,334696,NaN,NaN,NaN,5.9474,0.394936,1,6,6,6,6
avg_sales_lag12,334696,NaN,NaN,NaN,25.2277,5251.74,-82.13,0.85,1.02,1.29,2.56741e+06
avg_purchases_lag12,334696,NaN,NaN,NaN,2.0792,88.442,0.0983295,0.898333,1.04336,1.26648,50215.6
active_months_lag12,334696,NaN,NaN,NaN,11.5993,1.52014,1,12,12,12,12
category_4,334696,2,N,238596,NaN,NaN,NaN,NaN,NaN,NaN,NaN
city_id,334696,NaN,NaN,NaN,102.918,107.091,-1,-1,69,182,347
state_id,334696,NaN,NaN,NaN,11.8609,6.17689,-1,9,9,16,24
category_2,334696,NaN,NaN,NaN,2.33099,1.55577,1,1,1,4,5
merchant_category_1_yes,334696,NaN,NaN,NaN,0.021031,0.143488,0,0,0,0,1
merchant_category_1_no,334696,NaN,NaN,NaN,0.978969,0.143488,0,1,1,1,1
merchant_category_4_yes,334696,NaN,NaN,NaN,0.287126,0.452422,0,0,0,1,1
merchant_category_4_no,334696,NaN,NaN,NaN,0.712874,0.452422,0,0,1,1,1
most_sales_range_E,334696,NaN,NaN,NaN,0.529149,0.49915,0,0,1,1,1
most_sales_range_D,334696,NaN,NaN,NaN,0.35099,0.477281,0,0,0,1,1
most_sales_range_C,334696,NaN,NaN,NaN,0.101809,0.302397,0,0,0,0,1
most_sales_range_B,334696,NaN,NaN,NaN,0.0150495,0.12175,0,0,0,0,1
most_sales_range_A,334696,NaN,NaN,NaN,0.00300272,0.0547149,0,0,0,0,1
most_recent_purchases_range_E,334696,NaN,NaN,NaN,0.523786,0.499435,0,0,1,1,1
most_recent_purchases_range_D,334696,NaN,NaN,NaN,0.356105,0.478848,0,0,0,1,1
most_recent_purchases_range_C,334696,NaN,NaN,NaN,0.102015,0.302668,0,0,0,0,1
most_recent_purchases_range_B,334696,NaN,NaN,NaN,0.0150764,0.121857,0,0,0,0,1
most_recent_purchases_range_A,334696,NaN,NaN,NaN,0.00301766,0.0548504,0,0,0,0,1

In [54]:
train_data.to_csv('all_new/merchants_2.csv', index = False)